# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'YAQQNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YAQQNews


  pod 'YTKNetwork'
  pod 'MJRefresh'
  pod ‘MJExtension’
  pod ‘UITableView+FDTemplateLayoutCell’
  pod 'FDFullscreenPopGesture'
  pod 'YYWebImage'
  pod 'YYCategories' 
  pod 'TTTAttributedLabel'
  pod 'MLeaksFinder'
  pod ‘FMDB’
  pod 'IDMPhotoBrowser'
  pod ‘MBProgressHUD’
  # pod ‘DACircularProgress’
  pod 'SDWebImage'



end
